---
title: "Course Introduction"
output: 
  html_document:
    toc: no
---

\  

Hello and welcome to your QUADRAT DTP QUADstats course! This website compliments the QUADstats [MyAberdeen](https://abdn.blackboard.com/ultra/) course website and is mainly used to host exercises and associated exercise solutions and data files. You can find all other material for this QUADstats course on the MyAberdeen course site.   

\  

#### How to use this website

\  

The first thing you will need to do is check that you have both R and RStudio installed on your computer. Most (if not all) of you should already have these installed from when you attended the previous Introduction to R course. If you haven't used R and RStudio since (`r emo::ji("frowning_face")`) then its probably a good idea to update both to the latest versions. If for some reason you don't have R and RStudio installed then take a look at the **[<i class="fa fa-cog" aria-hidden="true"></i> Setup](setup.html)** link in the navbar above for further instructions on how to set up your computer.

This course will be delivered entirely online this year and will comprise a mixture of pre-recorded video lectures covering statistical theory and a series of live practical exercises and review sessions during which you will be able to ask questions and receive one-to-one help from the instructors. The recorded lectures will be hosted on our Virtual Learning Environment [MyAberdeen](https://abdn.blackboard.com/ultra/) and the live practical and review sessions with be delivered via Blackboard Collaborate. Full instructions on how to access Blackboard Collaborate will be provided before the course starts. 

This website mainly hosts the exercises you will complete each day and also the solutions for these exercises. You can access both by clicking on the **<i class="fa fa-book" aria-hidden="true"></i> Exercises** link on the navbar above (links will also be provided on the MyAberdeen website). To complete the exercises you will also need to download some data files to your computer which you can find by clicking on the **<i class="fa fa-download" aria-hidden="true"></i> Data** icon above and following the instructions.  

If you need to quickly brush up on your R skills or have forgotten how to do something (we've all been there!) please take a look at our new(ish) online open access Introduction to R book. There is a direct link to the book on the navbar above **<i class="fa fa-book" aria-hidden="true"></i> R Book**. Failing that, just give us a shout in one of the Blackboard collaborate sessions.

You can find links to additional resources, a suggested timetable, our contact details and a feedback form in **<i class="fa fa-question-circle" aria-hidden="true"></i> Info** link above.
\  
