---
title: 'Further Resources'
output: 
  html_document:
    toc: false
---

\  

### Learning R and statistics resources

\  

Here are some further resources for learning R, statistics and statistics with R. All of these resources are free and open source. This is by no means a comprehensive list so feel free to add your own by issuing a pull request on GitHub or [contact me](People.html) directly.

You can also find additional resources on the [R-Project website](https://cran.r-project.org/other-docs.html) and also this [GitHub repository](https://github.com/rstudio-education/rstats-ed).

\  

#### General R resources

- [R-Project](https://cran.r-project.org/other-docs.html): User contributed documentation

- [The R Journal](https://journal.r-project.org/): Journal of the R project for statistical computing

- [Swirl](http://swirlstats.com/): An R package that teaches you R from within R

- [RStudio's printable cheatsheets](https://www.rstudio.com/resources/cheatsheets/)

- [Rseek](http://rseek.org/): A custom Google search for R-related sites

\  

#### Free Statistics books and resources

\  

- [Learning statistics with R](https://learningstatisticswithr.com/book/): A fantastic book written by Danielle Navarro which comprehensively takes you through the basics up to more complicated statistical approaches.

- [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/): Covers the essential exploratory techniques for summarising data. Written by Roger D. Peng. 

- [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/index.html): A really nice book with an interesting take on learning and using statistics by Susan Holmes and Wolfgang Huber.

- [Answering questions with data](https://crumplab.github.io/statistics/index.html): Aimed at Psychology students but a good read for other students. Mostly lays out statistics in a more traditional way but pretty comprehensive. By Matthew J. C. Crump.

- [Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/): A comprehensive statistics book which also contains specific chapters covering a range of statistical concepts by David Dalpiaz.

- [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/): Covering generalised linear models and multilevel models in R but also has a good introduction to linear models. Written by Paul Roback and Julie Legler.

- [Mixed Models with R](https://m-clark.github.io/mixed-models-with-R/): A short introductory book on using and fitting mixed models in R by Michael Clark.

- [R for Data Science](https://r4ds.had.co.nz/): A tidyverse centric book for learning R and data science written by Hadley Wickham.

- [Statistical Inference via Data Science](https://moderndive.com/): Takes you from data wrangling through to inferential statistics using the tidyverse by Chester Ismay and Albert Y. Kim.


