---
title: 'Syllabus'
output: 
  html_document:
    toc: false
---

\  

The course will start at 09:30 each morning and finish at 17:00. We will break for a one hour lunch break around 12:30. However, everyone learns R and statistics in their own way and at their own pace so this syllabus should be treated as indicative rather than absolute. There will also be plenty of opportunities to take short breaks during the course.

The live sessions will be held on Blackboard Collaborate at the time indicated in the timetable below. The recorded video lectures will be hosted on MyAberdeen and you should watch them at the time indicated below.

<!--All teaching will be held in room FN113 in the Fraser Noble building (building No. 7 on [this map](images/uoa_map.png){target="_blank"} on the old Aberdeen campus).
-->

\  

\  

### Monday 8^th^ March 2021

\  

|09:30 - 10:15 | 10:15 - 11:30 | 11:30 - 12:30 | 12:30 - 13:30 |13:30 - 15:30 | 15:30 - 17:00 |
|:------------:|:-------------:|:-------------:|:-------------:|:------------:|:-------------:|
| Course introduction (ALL - live)  | Graphical data exploration (GDE) theory lecture (recorded MB) | GDE live practical (MB) | LUNCH |GDE live practical, Live review session (MB)| Linear models theory lectures (recorded AD), Linear models paper exercise |

\  

\  

### Tuesday 9^th^ March 2021 

\  

|09:30 - 10:30               | 10:30 - 12:30     | 12:30 - 13:30 |13:30 - 14:30    | 14:30 - 15:30      |15:30 - 17:00|
|:--------------------------:|:-----------------:|:-------------:|:---------------:|:------------------:|:-------------:|
|Linear model theory (recorded AD)|Linear models live practical (AD) – single continuous explanatory variable|LUNCH|Linear models live practical (AD) – single continuous explanatory variable, Live review session|Linear models theory (recorded AD) – single categorical explanatory variable|Linear models live practical (AD) – single categorical explanatory variable|

\  

\  

### Wednesday 10^th^ March 2021

\  

|09:30 - 11:30               | 11:30 - 12:30     | 12:30 - 13:30 |13:30 - 16:30    | 16:30 - 17:00      |
|:--------------------------:|:-----------------:|:-------------:|:---------------:|:------------------:|
|Linear model live practical (AD) – single categorical explanatory variable | Linear model theory (recorded ME) – categorical & continuous explanatory variables | LUNCH | Linear model live practical (ME) – categorical & continuous explanatory variables, Live review session (ME) | Catchup/course close (ALL - LIVE)|

\  

MB – Maarten Blaauw, ME – Mark Emmerson, AD – Alex Douglas

\  
